apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-kustomization
  namespace: flux
spec:
  interval: 1m
  path: ./clusters/my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: daniel-repo
  targetNamespace: default
